name: Genji App
url: http://genjiapp.com

blogDescription: Genji App Blogの更新情報

permalink: /blog/:year/:month/:day/:title.html

paginate: 5
paginate_path: "blog/page:num"

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "hard_wrap"]

historyURL: https://github.com/GenjiApp/genjiapp.github.io/commits/master/