name: Genji App
title: Genji App
url: http://genjiapp.com

blogDescription: Genji App Blogの更新情報

permalink: /blog/:year/:month/:day/:title.html

paginate: 5
paginate_path: "blog/page:num"

kramdown:
  input: GFM
  hard_wrap: true


historyURL: https://github.com/GenjiApp/genjiapp.github.io/commits/master/

plugins:
  - jekyll-sitemap
  - jekyll-paginate

timezone: Asia/Tokyo
future: true
